In [1]:
import numpy as np

#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])

# Activation function and its gradient

In [2]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x): 
    return x * (1 - x)

# Initialization of the parametors and Define the architecture

In [3]:
#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [4]:
#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [5]:
print(wh ,'\n','======','\n',bh,'\n','=======','\n',wout,'\n','=======','\n',bout)

[[0.57023182 0.2401222  0.67525465]
 [0.0263024  0.24988849 0.90624988]
 [0.21184577 0.97033858 0.90279449]
 [0.79755495 0.85761883 0.61842335]] 
 [[0.25046631 0.52437169 0.66161318]] 
 [[0.34588239]
 [0.3588325 ]
 [0.45491464]] 
 [[0.29838491]]


# Update the parametors

In [6]:
for i in range(epoch):

    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)
    
    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

In [7]:
print(output)

[[0.97570215]
 [0.96834985]
 [0.04841279]]


In [8]:
class Nnwk(object):
    def __init__(self,X=np.array([[]]),y=np.array([]),hiddenlayer_neurons = 3, output_neurons = 1, lr= 0.1):  
        self.X = X
        self.y = y
        self.inputlayer_neurons = self.X.shape[1]
        self.hiddenlayer_neurons = hiddenlayer_neurons
        self.output_neurons = output_neurons

        self.lr = lr
        self.wh=np.random.uniform(size=(self.inputlayer_neurons,self.hiddenlayer_neurons))
        self.bh=np.random.uniform(size=(1,self.hiddenlayer_neurons))
        self.wout=np.random.uniform(size=(hiddenlayer_neurons,self.output_neurons))
        self.bout=np.random.uniform(size=(1,self.output_neurons))
    #Sigmoid Function
    def sigmoid (self,x):
        return 1/(1 + np.exp(-x))

    #Derivative of Sigmoid Function
    def derivatives_sigmoid(self,x): 
        return x * (1 - x)
    
    def fit(self,epoc,data, target):
        self.X = data
        self.y = target
        for i in range(epoc):

            #Forward Propogation
            hidden_layer_input1=np.dot(self.X,self.wh)
            hidden_layer_input=hidden_layer_input1 + self.bh
            hiddenlayer_activations = self.sigmoid(hidden_layer_input)
            output_layer_input1=np.dot(hiddenlayer_activations,self.wout)
            output_layer_input= output_layer_input1+ self.bout
            output = self.sigmoid(output_layer_input)

            #Backpropagation
            E = self.y-output
            slope_output_layer = self.derivatives_sigmoid(output)
            slope_hidden_layer = self.derivatives_sigmoid(hiddenlayer_activations)
            d_output = E * slope_output_layer
            Error_at_hidden_layer = d_output.dot(self.wout.T)
            d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
            self.wout += hiddenlayer_activations.T.dot(d_output) *self.lr
            self.bout += np.sum(d_output, axis=0,keepdims=True) *self.lr
            self.wh += self.X.T.dot(d_hiddenlayer) *self.lr
            self.bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *self.lr
        return output

In [9]:
nnk = Nnwk()

In [13]:
#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])

In [14]:
nnk = Nnwk(X,y)

In [17]:
nnk.fit(500,X,y)

array([[0.82046143],
       [0.79287473],
       [0.37870182]])

In [18]:
from sklearn import datasets

In [19]:
iris = datasets.load_iris()

In [20]:
X = iris['data'][:,:3]
iris['target'] = (iris['target']!=0)*1
y =(iris['target']).reshape(-1,1)

In [28]:
#nnk1 = Nnwk()
np.dot(X,wh)

ValueError: shapes (150,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [22]:
pred =nnk1.fit(5000,X,y)
pred

ValueError: shapes (150,3) and (0,3) not aligned: 3 (dim 1) != 0 (dim 0)

In [77]:
(np.round(pred)-y).mean()

0.0

In [78]:
np.round(pred)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [79]:
X

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4],
       [5.4, 3.9, 1.7],
       [4.6, 3.4, 1.4],
       [5. , 3.4, 1.5],
       [4.4, 2.9, 1.4],
       [4.9, 3.1, 1.5],
       [5.4, 3.7, 1.5],
       [4.8, 3.4, 1.6],
       [4.8, 3. , 1.4],
       [4.3, 3. , 1.1],
       [5.8, 4. , 1.2],
       [5.7, 4.4, 1.5],
       [5.4, 3.9, 1.3],
       [5.1, 3.5, 1.4],
       [5.7, 3.8, 1.7],
       [5.1, 3.8, 1.5],
       [5.4, 3.4, 1.7],
       [5.1, 3.7, 1.5],
       [4.6, 3.6, 1. ],
       [5.1, 3.3, 1.7],
       [4.8, 3.4, 1.9],
       [5. , 3. , 1.6],
       [5. , 3.4, 1.6],
       [5.2, 3.5, 1.5],
       [5.2, 3.4, 1.4],
       [4.7, 3.2, 1.6],
       [4.8, 3.1, 1.6],
       [5.4, 3.4, 1.5],
       [5.2, 4.1, 1.5],
       [5.5, 4.2, 1.4],
       [4.9, 3.1, 1.5],
       [5. , 3.2, 1.2],
       [5.5, 3.5, 1.3],
       [4.9, 3.6, 1.4],
       [4.4, 3. , 1.3],
       [5.1, 3.4, 1.5],
       [5. , 3.5, 1.3],
       [4.5, 2.3

In [46]:
a = np.array([[1,2,3,2],[1,0,9,4]])
b = np.array([[1,2,4,5],[0,1,9,4],[10,3,0,4]]).T
print('size_a =  '+str(a.shape) + '  size_b =  ' + str(b.shape))

size_a =  (2, 4)  size_b =  (4, 3)


In [48]:
print(np.dot(a,b))
print(a@b)
print(a.dot(b))

[[27 37 24]
 [57 97 26]]
[[27 37 24]
 [57 97 26]]
[[27 37 24]
 [57 97 26]]


In [45]:
np.sum(b , axis = 0, keepdims = True)

array([[11,  6, 13, 13]])

In [49]:
import torch
torch.dot(a,b)

TypeError: dot(): argument 'input' (position 1) must be Tensor, not numpy.ndarray